/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 手机号 + 密码注册
         * @description 注册成功直接返回令牌（不要求再登录一次）。
         *     手机号在库中加密存储（ADR-0013），响应里一律脱敏。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RegisterRequest"];
                };
            };
            responses: {
                /** @description 注册成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["TokenPair"];
                        };
                    };
                };
                /** @description 参数错误（40001） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 手机号已被注册（40900） */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 手机号 + 密码登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LoginRequest"];
                };
            };
            responses: {
                /** @description 登录成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["TokenPair"];
                        };
                    };
                };
                /** @description 手机号或密码不正确（40100） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 账号已被禁用（40300） */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description 尝试过于频繁（42900） */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 用 Refresh Token 换新令牌
         * @description Refresh 一次性使用：换发新的一对令牌，旧 Refresh 立即作废（ADR-0012）。
         *     过期或已作废的 Refresh 返回 40101，前端跳登录。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["RefreshRequest"];
                };
            };
            responses: {
                /** @description 换发成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["TokenPair"];
                        };
                    };
                };
                /** @description Refresh Token 无效或已过期（40101） */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 退出登录
         * @description 作废当前 Refresh Token。**已签发的 Access Token 在剩余有效期（≤2 小时）内仍有效**——
         *     这是不引入 jti 黑名单的必然代价，见 ADR-0012。重复调用同样返回成功（幂等）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["LogoutRequest"];
                };
            };
            responses: {
                /** @description 已退出 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 当前用户资料 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
                401: components["responses"]["Unauthorized"];
            };
        };
        /**
         * 更新当前用户资料
         * @description 只传要改的字段；不传或传 `null` 表示不改。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["UpdateProfileRequest"];
                };
            };
            responses: {
                /** @description 更新后的资料 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
                /** @description 参数错误（40001） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/me/active-pet": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 切换当前宠物
         * @description 多宠家庭在这个账号上记住「当前在看谁」，跨浏览器一致。
         *     切到不属于自己的宠物、或已被删除的宠物，返回 40400。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ActivatePetRequest"];
                };
            };
            responses: {
                /** @description 切换后的资料 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["UserProfile"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 我的宠物列表
         * @description 默认只返回未删除的宠物。`deleted=true` 时返回**回收站**——软删除且仍在 30 天恢复期内的。
         *     宠物按账号维度数量很小，不分页。
         *
         *     **当前选中哪只不在这里**：那是账号上的偏好（`UserProfile.active_pet_id`），
         *     前端打开应用时读一次 `/users/me` 即可，不必让每个宠物都带一个 `is_active` 标记。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 是否查询回收站 */
                    deleted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Pet"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** 添加宠物 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PetCreateRequest"];
                };
            };
            responses: {
                /** @description 创建成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Pet"];
                        };
                    };
                };
                /** @description 参数错误（40001） */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{pet_id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: components["parameters"]["PetId"];
            };
            cookie?: never;
        };
        /** 宠物详情 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Pet"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        /**
         * 编辑宠物
         * @description 只传要改的字段；不传或传 `null` 表示不改。
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["PetUpdateRequest"];
                };
            };
            responses: {
                /** @description 更新后的宠物 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Pet"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        post?: never;
        /**
         * 删除宠物（软删除）
         * @description 软删除，30 天内可恢复（`POST /pets/{pet_id}/restore`）。
         *     按 `docs/conventions.md`「物理删除仅限账号注销场景」，过期后记录仍保留，只是不再可恢复。
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 已删除 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"];
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{pet_id}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 恢复被删除的宠物
         * @description 超过 30 天恢复期后返回 40400（前端提示「已超过恢复期」，与「不存在」同一处理）。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 恢复后的宠物 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["Pet"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{pet_id}/check-ins": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: components["parameters"]["PetId"];
            };
            cookie?: never;
        };
        /**
         * 某一天的打卡状态
         * @description 返回六项打卡各自的状态；不传 `date` 时按服务器当天（Asia/Shanghai）。
         *
         *     **任一项有记录即算当日已打卡**；不必凑齐六项（ADR-0018：桌面 Web 上强制六项会让人放弃）。
         */
        get: {
            parameters: {
                query?: {
                    /** @description 业务日期 `YYYY-MM-DD`；只能查过去 7 天到今天，更早的返回 40001 */
                    date?: string;
                };
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["CheckInDay"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        /**
         * 提交打卡（幂等）
         * @description 重复提交同「宠物 + 日期 + 分项」是**更新**而不是新增——用户改主意（饮食从「正常」改成「食欲差」）
         *     就是改这一条。可以一次提交多项（「全部正常」按钮即六项一起提交）。
         *
         *     补录：`date` 传过去 7 天内的日期即可，记录上会标 `backfilled=true`，不冒充当场录入。
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CheckInSubmitRequest"];
                };
            };
            responses: {
                /** @description 提交后的当日状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["CheckInDay"];
                        };
                    };
                };
                /** @description 参数错误（40001），含日期超出可补录窗口 */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                404: components["responses"]["NotFound"];
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{pet_id}/check-ins/item": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: components["parameters"]["PetId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 撤销某一项打卡
         * @description 填错了可以撤掉（幂等：本来就没有也返回成功）。只允许撤销可补录窗口内的记录。
         */
        delete: {
            parameters: {
                query: {
                    date: string;
                    /** @description 分项编号 1体重2饮食3排泄4行为5情绪6卫生 */
                    category: number;
                };
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 撤销后的当日状态 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["CheckInDay"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{pet_id}/check-ins/streak": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: components["parameters"]["PetId"];
            };
            cookie?: never;
        };
        /**
         * 连续打卡天数
         * @description 按「有记录的连续自然日」计算，**补录计入**（ADR-0018）；今天还没打卡不算断签
         *     （昨天有就算连续，今天补上即可）。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["CheckInStreak"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/pets/{pet_id}/health-score": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                pet_id: components["parameters"]["PetId"];
            };
            cookie?: never;
        };
        /**
         * 当日健康评分与近 7 天趋势
         * @description 五维 = 生理 / 行为 / 卫生 / 防疫 / 老年。**评分口径是「被观察到的健康」，不是医学评估**：
         *
         *     - 每维 = 70 × 近 7 天记录完整度 + 30 × (1 − 0.1 × 异常项数)；
         *     - 总分 = 已计入维度的等权平均；
         *     - **防疫**在没有疫苗/驱虫记录时不计入（`score: null`，前端显示「待录入」）；
         *     - **老年**专项未开启（年龄 < 7 岁且无慢病）时不计入（显示「未开启」）；
         *     - 一条记录都没有时 `total_score` 为 null，前端显示「还没有评分」而不是 0 分。
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    pet_id: components["parameters"]["PetId"];
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description 成功 */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["ApiResponse"] & {
                            data?: components["schemas"]["HealthScore"];
                        };
                    };
                };
                404: components["responses"]["NotFound"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterRequest: {
            /**
             * @description 中国大陆手机号
             * @example 13800138000
             */
            phone: string;
            /** @description 8–32 位，至少含一个字母与一个数字 */
            password: string;
            /** @description 可选；不传时按「宠物主人」生成 */
            nickname?: string;
        };
        /**
         * @description **登录不做口令格式校验**（不设 minLength 之类）：格式规则只属于注册，
         *     登录只有「匹配 / 不匹配」两种结果，不匹配一律 40100。
         */
        LoginRequest: {
            /** @example 13800138000 */
            phone: string;
            /** @example pet12345 */
            password: string;
        };
        RefreshRequest: {
            refresh_token: string;
        };
        LogoutRequest: {
            refresh_token: string;
        };
        TokenPair: {
            /** @description JWT；请求时放 Authorization: Bearer 请求头 */
            access_token: string;
            /** @description 不透明随机串，一次性使用（ADR-0012） */
            refresh_token: string;
            /** @description Access Token 剩余秒数（7200） */
            expires_in: number;
            user: components["schemas"]["UserProfile"];
        };
        UserProfile: {
            /** Format: int64 */
            id: number;
            /**
             * @description 脱敏手机号，形如 `138****8000`
             * @example 138****8000
             */
            phone: string;
            nickname: string;
            /** @description 头像 URL；未设置为 null */
            avatar?: string;
            /**
             * @description 0 未知 / 1 男 / 2 女
             * @enum {integer}
             */
            gender: 0 | 1 | 2;
            /**
             * Format: int64
             * @description 最近一次显式切换到的宠物。没切换过、或那只宠物已被删除时为 null——
             *     这时前端取宠物列表的第一只作为默认。
             */
            active_pet_id?: number;
            /** @example 2026-09-27 10:00:00 */
            created_at?: string;
        };
        /**
         * @description 「不改」与「清空」是两件事：字段不传或传 `null` = 不改；`avatar` 传空串 = 清空头像。
         *     `nickname` 是必填性字段（库里 NOT NULL），传空串返回 40001。
         */
        UpdateProfileRequest: {
            nickname?: string;
            /** @description 传空串表示清空 */
            avatar?: string;
            /** @enum {integer} */
            gender?: 0 | 1 | 2;
        };
        ActivatePetRequest: {
            /** Format: int64 */
            pet_id: number;
        };
        Pet: {
            /** Format: int64 */
            id: number;
            /** @example 豆豆 */
            name: string;
            /**
             * @description 1 犬 / 2 猫
             * @enum {integer}
             */
            species: 1 | 2;
            /**
             * @description 品种；未填为 null
             * @example 柯基
             */
            breed?: string;
            /**
             * @description 0 未知 / 1 公 / 2 母
             * @enum {integer}
             */
            gender: 0 | 1 | 2;
            /**
             * @description 生日 `YYYY-MM-DD`；未填为 null
             * @example 2023-05-01
             */
            birthday?: string;
            /**
             * @description 体重 kg，两位小数。**字符串**——浮点在 JS 里会丢精度（ADR-0011）
             * @example 12.50
             */
            weight?: string;
            avatar?: string;
            /** @description 是否绝育 */
            is_sterilized?: boolean;
            /** @description 是否有慢病（触发专项照护，见 */
            is_chronic?: boolean;
            /** @description 慢病描述；`is_chronic=false` 时为 null */
            chronic_desc?: string;
            /**
             * @description 仅回收站里有值——可恢复的截止时间（删除后 30 天）
             * @example 2026-10-27 10:00:00
             */
            restorable_until?: string;
            /** @example 2026-09-27 10:00:00 */
            created_at?: string;
            /** @example 2026-09-27 10:00:00 */
            updated_at?: string;
        };
        PetCreateRequest: {
            /** @example 豆豆 */
            name: string;
            /** @enum {integer} */
            species: 1 | 2;
            breed?: string;
            /**
             * @default 0
             * @enum {integer}
             */
            gender: 0 | 1 | 2;
            /**
             * @description 生日格式 YYYY-MM-DD，不得晚于今天
             * @example 2023-05-01
             */
            birthday?: string;
            /**
             * @description 体重 kg，两位小数；范围 0.01–999.99
             * @example 12.50
             */
            weight?: string;
            avatar?: string;
            /** @default false */
            is_sterilized: boolean;
            /** @default false */
            is_chronic: boolean;
            /** @description 慢病描述；`is_chronic=true` 时必填 */
            chronic_desc?: string;
        };
        /**
         * @description 「不改」与「清空」是两件事：字段不传或传 `null` = 不改；
         *     `breed` / `avatar` 传空串 = 清空。
         *     `chronic_desc` 传空串同样表示清空，但**只在 `is_chronic=false` 时成立**——
         *     标记为慢病时它是必填项，传空会返回 40001。
         *     `name` 传空串返回 40001；`weight` / `birthday` 不接受空串（要改就得给合法值）。
         */
        PetUpdateRequest: {
            name?: string;
            /** @enum {integer} */
            species?: 1 | 2;
            breed?: string;
            /** @enum {integer} */
            gender?: 0 | 1 | 2;
            /** @example 2023-05-01 */
            birthday?: string;
            /** @example 12.50 */
            weight?: string;
            avatar?: string;
            is_sterilized?: boolean;
            is_chronic?: boolean;
            chronic_desc?: string;
        };
        CheckInSubmitRequest: {
            /**
             * @description 业务日期 `YYYY-MM-DD`。传今天=当场录入；传过去 7 天内=补录（记录标 `backfilled`）
             * @example 2026-09-27
             */
            date: string;
            /** @description 本次提交的分项；同一个日期可以分多次提交（例如先记体重，晚上再补其他的） */
            items: components["schemas"]["CheckInItemInput"][];
        };
        CheckInItemInput: {
            /**
             * @description 1 体重 / 2 饮食 / 3 排泄 / 4 行为 / 5 情绪 / 6 卫生
             * @enum {integer}
             */
            category: 1 | 2 | 3 | 4 | 5 | 6;
            /**
             * @description 用户是否标注为异常。**评分按它扣分**，所以是打卡里最有信息量的一个字段
             * @default false
             */
            abnormal: boolean;
            /**
             * @description 结构化取值：体重是数字字符串（kg），其余是选项值（如 normal / low / high）
             * @example 12.50
             */
            value?: string;
            /** @description 补充说明（异常时建议填写） */
            note?: string;
        };
        CheckInItem: {
            /** @enum {integer} */
            category: 1 | 2 | 3 | 4 | 5 | 6;
            /** @example 体重 */
            name: string;
            /** @description 该分项当天是否已有记录 */
            filled?: boolean;
            abnormal: boolean;
            value?: string;
            note?: string;
            /** @description 该条是否为补录 */
            backfilled?: boolean;
        };
        CheckInDay: {
            /** @example 2026-09-27 */
            date: string;
            items: components["schemas"]["CheckInItem"][];
            /** @description 已填分项数（进度 n/6） */
            completed_count: number;
            /** @example 6 */
            total_count: number;
            /** @description 当日是否已打卡——**任一项有记录即为 true**（ADR-0018），不要求凑齐六项 */
            done: boolean;
            /** @description 本次查询的日期是否为补录（今天之前的日期） */
            backfilled?: boolean;
        };
        CheckInStreak: {
            /** @description 连续打卡天数（有记录的连续自然日；补录计入；断签归零） */
            streak_days: number;
            /** @description 今天是否已经有记录。今天未打卡不算断签——昨天有记录就仍算连续 */
            checked_today: boolean;
            /**
             * @description 最长连续段，**按现有记录计算**（不是历史峰值）：删掉某天的记录，那段也就不存在了。
             *     权益若要按连续天数发奖（#113），需要单独存历史峰值。
             */
            longest_streak_days?: number;
        };
        HealthScoreDimension: {
            /** @enum {string} */
            key: "physiology" | "behavior" | "hygiene" | "epidemic" | "elderly";
            /** @example 生理 */
            name: string;
            /** @description 该维得分；为 null 表示未计入（见 `excluded_reason`） */
            score?: number;
            /** @description 是否计入了总分 */
            included: boolean;
            /** @description 未计入的原因，前端直接展示：「待录入」（防疫无数据）/「未开启」（老年专项）/「暂无记录」 */
            excluded_reason?: string;
            /** @description 一句话说明分数怎么来的，例如「近 7 天记录 4 天，异常 1 次」——评分必须可解释 */
            detail?: string;
        };
        HealthScore: {
            /** @description 总分；一条记录都没有时为 null（前端显示「还没有评分」，不要显示 0 分） */
            total_score?: number;
            /** @description 中性档位文案：良好 / 尚可 / 需关注 / 暂无数据 */
            grade: string;
            dimensions: components["schemas"]["HealthScoreDimension"][];
            /** @description 近 7 天总分序列（缺失的日期不出现），供首页趋势展示 */
            trend?: {
                /** @example 2026-09-27 */
                date?: string;
                total_score?: number;
            }[];
            /** @example 2026-09-27 */
            calc_date?: string;
            /** @description 口径声明，前端必须展示：评分是「被观察到的健康」，不是医学评估 */
            disclaimer?: string;
        };
        ApiResponse: {
            /** @description 0=成功，非 0=业务错误码（见文件末尾的 x-error-codes） */
            code: number;
            /** @description 提示文案，前端直接展示 */
            message: string;
            /** @description 业务数据，可为对象 / 数组 / null */
            data?: unknown;
            /** @description 全链路追踪 ID */
            request_id?: string;
        };
    };
    responses: {
        /** @description 未登录或 Token 已过期（40100 / 40101） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 资源不存在（40400） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        PetId: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
