/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @description 0=成功，非 0=业务错误码（见文件末尾的 x-error-codes） */
            code: number;
            /** @description 提示文案，前端直接展示 */
            message: string;
            /** @description 业务数据，可为对象 / 数组 / null */
            data?: unknown;
            /** @description 全链路追踪 ID */
            request_id?: string;
        };
        PageResult: {
            list: unknown[];
            page: number;
            /** @default 20 */
            page_size: number;
            total: number;
            has_more: boolean;
        };
    };
    responses: {
        /** @description 未登录或 Token 已过期（40100 / 40101） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 无权限（40300） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 资源不存在（40400） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 数据冲突，如重复提交（40900） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /**
         * @description 请求过于频繁（42900）。两道闸都会给这个码：接口级限流（ADR-0028）与
         *     同一手机号的登录失败次数（ADR-0012）。两者的 `message` 都写明了要等多久。
         *     **`Retry-After` 头目前只有接口级限流会给**：登录失败锁定由异常处理器返回，
         *     那一层没有设置响应头的位置，前端对它只能读 `message`。
         */
        TooManyRequests: {
            headers: {
                /** @description 窗口剩余秒数（HTTP 标准头）。仅接口级限流返回；据此做倒计时，读不到就退回解析 `message` */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 服务器内部错误（50000） */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 服务不可用（50300） */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description 客户端生成的唯一键（建议 UUID），同一逻辑写操作重试时保持不变；最长 200 字符 */
        IdempotencyKey: string;
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
