/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type paths = Record<string, never>;
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiResponse: {
            /** @description 0=成功，非 0=业务错误码（见文件末尾的 x-error-codes） */
            code: number;
            /** @description 提示文案，前端直接展示 */
            message: string;
            /** @description 业务数据，可为对象 / 数组 / null */
            data?: unknown;
            /** @description 全链路追踪 ID */
            request_id?: string;
        };
        PageResult: {
            list: unknown[];
            page: number;
            /** @default 20 */
            page_size: number;
            total: number;
            has_more: boolean;
        };
    };
    responses: {
        /** @description 未登录或 Token 已过期（40100 / 40101） */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 无权限（40300） */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 资源不存在（40400） */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 数据冲突，如重复提交（40900） */
        Conflict: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 请求过于频繁（42900） */
        TooManyRequests: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 服务器内部错误（50000） */
        ServerError: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description 服务不可用（50300） */
        ServiceUnavailable: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        Page: number;
        PageSize: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
